version: "3.3"

name: networking

networks:
  default:
    driver: bridge
  multimedia_default:
    external: true
  downloads_default:
    external: true
  utilities_default:
    external: true
  extras_default:
    external: true
  monitoring_default:
    external: true
  nextcloud_default:
    external: true

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    networks:
      - default
      - multimedia_default
      - downloads_default
      - utilities_default
      - extras_default
      - monitoring_default
      - nextcloud_default
    pull_policy: missing
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"
      - "--entryPoints.zabbix-tcp.address=:10051"
      - "--entryPoints.zabbix-udp.address=:10051/udp"
      - "--ping=true"
      - "--ping.entryPoint=ping"
      - "--entrypoints.ping.address=:8081"
      - "--certificatesresolvers.stepca.acme.caserver=https://step-ca.networking.bellecerise.local:8999/acme/acme/directory"
      - "--certificatesresolvers.stepca.acme.storage=/stepca/acme.json"
      - "--certificatesresolvers.stepca.acme.httpchallenge=true"
      - "--certificatesresolvers.stepca.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.stepca.acme.email=admin@bellecerise.be"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=stepca"  
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=8080"
    ports:
      - "${NETWORK_INTERFACE}:80:80"
      - "${NETWORK_INTERFACE}:443:443"
      - "${NETWORK_INTERFACE}:8080:8080"
      - "${NETWORK_INTERFACE}:10051:10051/tcp"
      - "${NETWORK_INTERFACE}:10051:10051/udp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/fastpool/system/processes/traefik/stepca:/stepca"
      - "/mnt/fastpool/system/cert/root_ca.crt:/certs/root_ca.crt:ro"
    environment:
      - LEGO_CA_CERTIFICATES=/certs/root_ca.crt
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/ping"]
      interval: 25s
      timeout: 5s
      retries: 10
      start_period: 30s

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=whoami-https-redirect"
      - "traefik.http.routers.whoami-secure.rule=Host(`whoami.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.whoami-secure.entrypoints=web-secure"
      - "traefik.http.routers.whoami-secure.tls=true"
      - "traefik.http.routers.whoami-secure.tls.certresolver=stepca"  

  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    networks:
      - default
    pull_policy: missing
    restart: unless-stopped
    user: ${APP_USER}:${APP_GROUP}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.step-ca.rule=Host(`step-ca.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.step-ca.entrypoints=web,web-secure"
      - "traefik.http.routers.step-ca.tls=true"
      - "traefik.http.routers.step-ca.tls.certresolver=stepca"
    secrets:
      - source: step-ca-password
        target: /home/step/secrets/password
    ports:      
      - "${NETWORK_INTERFACE}:8999:9000"
    volumes:
      - /mnt/fastpool/system/processes/step-ca:/home/step
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/home/step/certs/root_ca.crt", "https://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  step-ca-password:
    file: /mnt/fastpool/system/processes/secrets/step-ca-password.txt
