version: "3.3"

name: multimedia

networks:
  default:
    driver: bridge
  utilities_default:
    external: true
  downloads_default:
    external: true

services:
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    networks:
      - default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.emby-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.emby.rule=Host(`emby.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.emby.entrypoints=web"
      - "traefik.http.routers.emby.middlewares=emby-https-redirect"
      - "traefik.http.routers.emby-secure.rule=Host(`emby.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.emby-secure.entrypoints=web-secure"
      - "traefik.http.routers.emby-secure.tls=true"
      - "traefik.http.routers.emby-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:8096:8096/tcp
      - ${NETWORK_INTERFACE}:8920:8920/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/emby/config:/config
      - /mnt/fastpool/system/multimedia/emby/system:/mnt/system
      - /mnt/rightpool/multimedia/movies:/mnt/movies
      - /mnt/rightpool/multimedia/series:/mnt/series
      - /mnt/rightpool/multimedia/music:/mnt/music
      - /mnt/rightpool/multimedia/pictures:/mnt/pictures
      - /mnt/leftpool/multimedia/phones:/mnt/phones
      - /mnt/rightpool/multimedia/games:/mnt/games
      - /mnt/rightpool/backup/automated/emby:/mnt/backup
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/emby/System/Info/Public" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - default
      - downloads_default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.entrypoints=web-secure"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:8989:8989/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/sonarr:/config
      - /mnt/rightpool/downloads:/downloads
      - /mnt/rightpool/multimedia/series:/tv
      - /mnt/rightpool/backup/automated/sonarr:/backup
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - default
      - downloads_default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.entrypoints=web-secure"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:7878:7878/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/radarr:/config
      - /mnt/rightpool/downloads:/downloads
      - /mnt/rightpool/multimedia/movies:/movies
      - /mnt/rightpool/backup/automated/radarr:/backup
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - default
      - downloads_default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.lidarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.lidarr.entrypoints=web"
      - "traefik.http.routers.lidarr.middlewares=lidarr-https-redirect"
      - "traefik.http.routers.lidarr-secure.rule=Host(`lidarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.lidarr-secure.entrypoints=web-secure"
      - "traefik.http.routers.lidarr-secure.tls=true"
      - "traefik.http.routers.lidarr-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:8686:8686/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/lidarr:/config
      - /mnt/rightpool/downloads:/downloads
      - /mnt/rightpool/multimedia/music:/music
      - /mnt/rightpool/backup/automated/lidarr:/backup
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.routers.bazarr.middlewares=bazarr-https-redirect"
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.bazarr-secure.entrypoints=web-secure"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.tls.certresolver=stepca"
    ports:
      - 6767:6767
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    volumes:
      - /mnt/fastpool/system/multimedia/bazarr:/config
      - /mnt/rightpool/multimedia/movies:/movies
      - /mnt/rightpool/multimedia/series:/tv
      - /mnt/rightpool/backup/automated/bazarr:/backup
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    networks:
      - default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.organizr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.organizr.rule=Host(`organizr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.organizr.entrypoints=web"
      - "traefik.http.routers.organizr.middlewares=organizr-https-redirect"
      - "traefik.http.routers.organizr-secure.rule=Host(`organizr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.organizr-secure.entrypoints=web-secure"
      - "traefik.http.routers.organizr-secure.tls=true"
      - "traefik.http.routers.organizr-secure.tls.certresolver=stepca"
      - "traefik.http.routers.organizr-empty.rule=Host(`${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.organizr-empty.entrypoints=web"
      - "traefik.http.routers.organizr-empty.middlewares=organizr-https-redirect"
      - "traefik.http.routers.organizr-empty-secure.rule=Host(`${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.organizr-empty-secure.entrypoints=web-secure"
      - "traefik.http.routers.organizr-empty-secure.tls=true"
      - "traefik.http.routers.organizr-empty-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:81:80/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/organizr:/config
    environment:
      - PGID=${APP_USER}
      - PUID=${APP_GROUP}
      - TZ=${APP_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    user: "${APP_USER}:${APP_GROUP}"
    networks:
      - default
    pull_policy: missing
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.seerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.seerr.rule=Host(`seerr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.seerr.entrypoints=web"
      - "traefik.http.routers.seerr.middlewares=seerr-https-redirect"
      - "traefik.http.routers.seerr-secure.rule=Host(`seerr.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.seerr-secure.entrypoints=web-secure"
      - "traefik.http.routers.seerr-secure.tls=true"
      - "traefik.http.routers.seerr-secure.tls.certresolver=stepca"
    ports:
      - ${NETWORK_INTERFACE}:5055:5055/tcp
    volumes:
      - /mnt/fastpool/system/multimedia/seerr:/app/config
    environment:
      - TZ=${APP_TIMEZONE}
      - JELLYFIN_TYPE=emby
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 30s
